### ISSUE TITLE
关于训练数据集的处理

### ISSUE THREAD

**Issue by yifeipet** [NJUVISION/NIC#12]
您好。您们的这个项目的工作非常出色，代码非常详细，我读了受益匪浅。对于训练数据集的处理，能否也提供代码，我有COCO数据集，不过不知道，你们是如何得到2万个256x256的patch的。我之前分的COCO数据集的patch用的是nonoverlapped的方法，有23万多个，COCO 2017的图片有10万多个。
如果不便分享代码，也请教下思路。感谢。

**Comment by tongxyh** [comment]
你好，非常感谢对这个工作的关注。关于具体训练集的准备我这里也没有一种非常标准的做法，思路上就是在比如COCO数据集中进行随机的尺度缩放和随机位置crop来生成指定数量的固定尺寸（如256x256）的数据集。希望能够对你有帮助。

Tong

**Comment by yifeipet** [comment]
> 你好，非常感谢对这个工作的关注。关于具体训练集的准备我这里也没有一种非常标准的做法，思路上就是在比如COCO数据集中进行随机的尺度缩放和随机位置crop来生成指定数量的固定尺寸（如256x256）的数据集。希望能够对你有帮助。
> 
> Tong

十分感谢。祝科研顺利，生活愉快！
