### ISSUE TITLE
Questions about the pretrained models

### ISSUE THREAD

**Issue by JXH-SHU** [NJUVISION/NIC#3]
The difference between the mse200.pkl and the mse200p.pkl? And the difference between ckpts file and row-context-ckpts file?

**Comment by NJUVISION** [comment]
Hi, sorry for the late response. Actually all xxx.pkl files with no 'p' are checkpoints for models except the context model, while xxxp.pkl with 'p' are checkpoints for the context model. Hope this information can help you.
Besides, the row-context-ckpts are checkpoints for models with faster parallel context decoding. But it is not included in the updated link now. Please refer to the new link [here](https://box.nju.edu.cn/d/77ed09b10706429e9b09/) for pertained models.

**Comment by JXH-SHU** [comment]
Thanks for your reply!!!
