### ISSUE TITLE
Broken download link for pretrained weights

### ISSUE THREAD

**Issue by rezafuru** [NJUVISION/NIC#7]
Hello,

I need the pre-trained weights for some experiments but the provided link seems broken: https://box.nju.edu.cn/d/b59340c5eef249cda4e4/

Could you please reupload the weights and share the link?

BR

**Comment by NJUVISION** [comment]
Hi, the link for downloading pre-trained models has been updated. please check the new link [here](https://box.nju.edu.cn/d/77ed09b10706429e9b09/).

**Comment by rezafuru** [comment]
Perfect, and many thanks for making your amazing work open source!

BR

**Comment by tzayuan** [comment]
@rezafuru ,

I want to know that if you generate reconstructure picture by pretrain model? Thanks a lot!
